image: maven:3.3.9-jdk-8

services:
- selenium/standalone-chrome:latest
variables:
  selenium_remote_url: "http://selenium__standalone-chrome:5555/wd/hub/"
  
build:
  script: 
   - echo "Building project with maven"
   - mvn install -B
