image: maven:3.3.9-jdk-8

services:
- selenium/standalone-chrome:latest
variables:
  SELENIUM_REMOTE_URL: "http://gitlab-selenium-server:6666/wd/hub"
  GITLAB_TARGET_SELENIUM_REMOTE_URL: "http://selenium__standalone-chrome:6666/wd/hub"

  
build:
  script: 
   - echo "Building project with maven"
   - mvn install -B
